### ISSUE TITLE
Null object return

### ISSUE THREAD

**Issue by slaymantis** [sounden/phinstagram#2]
Hi

i seem to get this error when trying to load some accounts
// 20171021150004
// https://www.domain.com
/instagram/phinstagram.php?username=fitchicksociety

{
  "error": 4
}

**Comment by slaymantis** [comment]
Ok i just added this to the php and it sorted out the scraper
below line 57
$json_string = substr($json_string, 0, strpos($json_string,'!function'));

**Comment by sounden** [comment]
Great, Thanks will look into this and update the code. Maybe you want to do a pull request?
